/*
   Inserting all Sundyays in a Year.
*/

-- INSERT INTO mst_holiday (hdate, holiday_remark)
SELECT 
    CONCAT(d, ' 00:00:00') AS hdate,
    'SUNDAY' AS holiday_remark
FROM (
    SELECT DATE('2026-01-01') + INTERVAL n DAY AS d
    FROM (
        SELECT a.a + b.a * 10 + c.a * 100 AS n
        FROM
            (SELECT 0 a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
             UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
            (SELECT 0 a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
             UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
            (SELECT 0 a UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3) c
    ) numbers
    WHERE DATE('2026-01-01') + INTERVAL n DAY <= '2026-12-31'
) dates
WHERE DAYOFWEEK(d) = 1;
